baseURL = 'http://example.org/'
languageCode = 'id-id'
title = 'Futami Yarn'
enableRobotsTXT = true


[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

# [params]
# mainSections = ["posts"]

[params.algolia]
vars = ["title", "description"]
# params = ["tags"]

[markup.goldmark.renderer]
unsafe= true

# [markup]
#   [markup.highlight]
#     anchorLineNos = false
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ''
#     hl_inline = false
#     lineAnchors = ''
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = false
#     noHl = false
#     style = 'monokai'
#     tabWidth = 4